categories:
  教材:
    keywords:
      - 教程
      - 教材
      - 官方
  综合知识:
    keywords:
      - 综合知识
      - 上午题
      - 选择题
  案例分析:
    keywords:
      - 案例
      - 下午题
  论文:
    keywords:
      - 论文
      - 范文
      - 写作
  真题:
    keywords:
      - 真题
      - 答案
      - 解析
  笔记:
    keywords:
      - 笔记
      - 总结
      - 重点
  其他:
    keywords: []